### ISSUE TITLE
Verses with type 'title' has wrong verse number

### ISSUE THREAD

**Issue by agallio** [sonnylazuardi/alkitab-api#1]
**Issue Detail** : When querying the chapter API, it sends verses with type content and title. But the 'title' type has wrong verse number. It shows verse 7 but in that chapter it's verse 1.

**Steps to Reproduce** : 
* Query the chapter API
* Fill the passage arguments 
* Send the query

**Expected Result** : The verse with type 'title' same with the type 'content' below it. For example the verse number below the title is 1, so the title must be 1

**Screenshot** :
![image](https://user-images.githubusercontent.com/22767465/50468018-5e3aab80-09d8-11e9-9618-efb2465ea816.png)

Thanks :+1:

**Comment by sonnylazuardi** [comment]
Fixed with this commit, thanks for the report 👍 https://github.com/sonnylazuardi/alkitab-api/commit/c1642e5db6ddb30b0af09b1ed5847ea7e9919003
